# Generated by Django 4.1.1 on 2022-10-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='_kategoriya nomi', max_length=255),
        ),
    ]
