# Generated by Django 4.1.1 on 2022-10-30 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoriya ', 'verbose_name_plural': 'Kategoriyalar '},
        ),
        migrations.AlterModelTable(
            name='category',
            table='Categories',
        ),
    ]
