# Generated by Django 4.1.1 on 2022-10-29 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_alter_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Mahsulot nomini kiriting', max_length=600, verbose_name='Mahsulot nomi')),
                ('image', models.ImageField(help_text='Mahsulot rasmini yuklang', upload_to='product-images', verbose_name='Mahsulot rasmi')),
                ('description', models.TextField(help_text='Mahsulot haqida kiriting', verbose_name='Mahsulot haqida qisqacha')),
                ('cost', models.IntegerField(help_text='Mahsulot narxini kiriting', verbose_name='Mahsulot narxi')),
                ('discount', models.IntegerField(default=0, help_text='Mahsulot chegirma narxini kiriting', verbose_name='Chegirma narxi')),
                ('viewed', models.IntegerField(blank=True, help_text="Ko'rilganlari soni", null=True, verbose_name="Ko'rilganlari soni")),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Mahsulot kategoriyasini tanlang', on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name='Mahsulot kategoriyasi')),
            ],
            options={
                'verbose_name': 'Mahsulot ',
                'verbose_name_plural': 'Mahsulotlar ',
                'db_table': 'Products',
            },
        ),
    ]
